apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-ticker-deployment
  labels:
    app: stock-ticker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-ticker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stock-ticker
    spec:
      containers:
        - name: stock-ticker
          image: shaz900/stock-ticker-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m  # Minimum CPU requested for the container
              memory: 2Gi  # Minimum memory requested for the container
            limits:
              cpu: 1000m  # Maximum CPU allowed for the container
              memory: 4Gi  # Maximum memory allowed for the container
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          env:
            - name: SYMBOL
              valueFrom:
                configMapKeyRef:
                  name: stock-ticker-config
                  key: SYMBOL
            - name: NDAYS
              valueFrom:
                configMapKeyRef:
                  name: stock-ticker-config
                  key: NDAYS
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: stock-ticker-secret
                  key: APIKEY

